name = "ImagePFM"
uuid = "de255290-5529-4d77-9c46-251ebffccf2e"
authors = ["Samuele-Colombo <samuele.colombo1@studenti.unimi.it>"]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
